# docker-compose.yml
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: plano-mestre-db
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=plano_mestre_user
      - POSTGRES_PASSWORD=plano_mestre_pass
      - POSTGRES_DB=plano_mestre_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: